## GET contacts
//GET http://localhost:3000/users

## GET contact by ID
GET http://localhost:3000/users/682581dd724198380dd3ff4b

## POST contact
POST http://localhost:3000/users HTTP/1.1
content-Type: application/json

{
    "firstName": "Billy", 
    "lastName": "Bob", 
    "email": "testing@123.com", 
    "favoriteColor": "blue", 
    "birthday": "1990-01-01"
}
